import type { Metadata } from "next";
import { REM, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar"
import { Toaster } from "sonner"

const rem = REM({
  variable: "--font-rem",
  subsets: ["latin"],
  weight: "300",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tooken changeit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rem.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased flex flex-col h-screen overflow-hidden`}
      >
        <Navbar />
        <main className="flex-1 overflow-y-auto mt-16">
          {children}
          <Toaster position="bottom-left" richColors />
        </main>
      </body>
    </html>
  );
}
